const content = [
    {
      id: 1,
      title: 'butteerCheese pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `This pancake recipe produces thick, fluffy, and all-around delicious pancakes with just a few ingredients that are probably already in your kitchen`,
    },
    {
      id: 2,
      title: 'Turkey Burger',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `The best burgers offer a combination of tastes and textures – sweet, sour, salt – with a bit of crunch. The patty needs to be juicy, the bun soft but sturdy. `,
    },
    {
      id: 3,
      title: 'Mighty milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `A thoroughly shaken or blended drink made of milk, a flavoring syrup, and often ice cream. a Vennila milkshake.`,
    },
    {
      id: 4,
      title: 'Bread Butter',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: ` Creamy eggy filling, seasoned with scintillating flavours and finely chopped vegetables, `,
    },
    {
      id: 5,
      title: 'Hamburger Patty',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `The patty needs to be juicy, the bun soft but sturdy, and you want the meat/bun/accompaniment ratio to be even from first to last bite. `,
    },
    {
      id: 6,
      title: 'oreo Cream',
      category: 'shakes',
      price: 25.99,
      img: './images/item-6.jpeg',
      desc: `A thoroughly shaken or blended drink made of milk, a flavoring syrup, and often ice cream.`,
    },
    {
      id: 7,
      title: 'bacon Chicken',
      category: 'breakfast',
      price: 10.99,
      img: './images/item-7.jpeg',
      desc: `A sandwich consisting of a patty made from ground chicken, served in a bun, typically hot and often with other ingredients.`,
    },
    {
      id: 8,
      title: 'Wild salmon burger',
      category: 'lunch',
      price: 15.99,
      img: './images/item-8.jpeg',
      desc: `A salmon burger is a type of fishcake made mostly from salmon in the style of a hamburger. The salmon requires a binder to make it stick together.`,
    },
    {
      id: 9,
      title: 'Strawberry Shake',
      category: 'shakes',
      price: 20.99,
      img: './images/str3.jpg',
      desc: ` A delicious drink made with strawberries, milk, ice cream and flavoring ingredients like vanilla extract or strawberry syrup. Optionally topped with whipped cream.`,
    },
  ];
  export default content;